version: 2.1

orbs:
  node: circleci/node@5.0.1
  aws-cli: circleci/aws-cli@1.3.1
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1

jobs:
  build-and-deploy:
    docker:
      - image: node:18
        environment:
          NODE_ENV: production
    steps:
      - checkout
      - node/install:
          version: "18"
      - aws-cli/setup
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install
            npm install webpack@latest --save-dev
      - run:
          name: Front-End Build
          command: |
            NODE_OPTIONS=--openssl-legacy-provider npm run frontend:build
      - run:
          name: Front-End Deploy
          command: |
            npm run frontend:deploy
      - run:
          name: Back-End Install
          command: |
            npm run api:install
      - run:
          name: Back-End Build
          command: |
            npm run api:build
      - run:
          name: Back-End Deploy
          command: |
            npm run api:deploy

workflows:
  build-and-deploy:
    jobs:
      - build-and-deploy:
          filters:
            branches:
              only:
                - master
